//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beamable.Server.Clients
{
    using System;
    using Beamable.Platform.SDK;
    using Beamable.Server;
    
    
    /// <summary> A generated client for <see cref="Beamable.Microservices.BackendService"/> </summary
    public sealed class BackendServiceClient : MicroserviceClient, Beamable.Common.IHaveServiceName
    {
        
        public BackendServiceClient(BeamContext context = null) : 
                base(context)
        {
        }
        
        public string ServiceName
        {
            get
            {
                return "BackendService";
            }
        }
        
        /// <summary>
        /// Call the ServerCall method on the BackendService microservice
        /// <see cref="Beamable.Microservices.BackendService.ServerCall"/>
        /// </summary>
        public Beamable.Common.Promise<Beamable.Common.Unit> ServerCall()
        {
            System.Collections.Generic.Dictionary<string, object> serializedFields = new System.Collections.Generic.Dictionary<string, object>();
            return this.Request<Beamable.Common.Unit>("BackendService", "ServerCall", serializedFields);
        }
    }
    
    internal sealed class MicroserviceParametersBackendServiceClient
    {
    }
    
    [BeamContextSystemAttribute()]
    public static class ExtensionsForBackendServiceClient
    {
        
        [Beamable.Common.Dependencies.RegisterBeamableDependenciesAttribute()]
        public static void RegisterService(Beamable.Common.Dependencies.IDependencyBuilder builder)
        {
            builder.AddScoped<BackendServiceClient>();
        }
        
        public static BackendServiceClient BackendService(this Beamable.Server.MicroserviceClients clients)
        {
            return clients.GetClient<BackendServiceClient>();
        }
    }
}
