//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beamable.Server.Clients
{
    using System;
    using Beamable.Platform.SDK;
    using Beamable.Server;
    
    
    /// <summary> A generated client for <see cref="Beamable.Microservices.UserGroupService"/> </summary
    public sealed class UserGroupServiceClient : MicroserviceClient, Beamable.Common.IHaveServiceName
    {
        
        public UserGroupServiceClient(BeamContext context = null) : 
                base(context)
        {
        }
        
        public string ServiceName
        {
            get
            {
                return "UserGroupService";
            }
        }
        
        /// <summary>
        /// Call the Test method on the UserGroupService microservice
        /// <see cref="Beamable.Microservices.UserGroupService.Test"/>
        /// </summary>
        public Beamable.Common.Promise<string> Test()
        {
            System.Collections.Generic.Dictionary<string, object> serializedFields = new System.Collections.Generic.Dictionary<string, object>();
            return this.Request<string>("UserGroupService", "Test", serializedFields);
        }
        
        /// <summary>
        /// Call the SaveUser method on the UserGroupService microservice
        /// <see cref="Beamable.Microservices.UserGroupService.SaveUser"/>
        /// </summary>
        public Beamable.Common.Promise<System.Threading.Tasks.Task> SaveUser(long gamerTag, string username)
        {
            object raw_gamerTag = gamerTag;
            object raw_username = username;
            System.Collections.Generic.Dictionary<string, object> serializedFields = new System.Collections.Generic.Dictionary<string, object>();
            serializedFields.Add("gamerTag", raw_gamerTag);
            serializedFields.Add("username", raw_username);
            return this.Request<System.Threading.Tasks.Task>("UserGroupService", "SaveUser", serializedFields);
        }
        
        /// <summary>
        /// Call the GetUsername method on the UserGroupService microservice
        /// <see cref="Beamable.Microservices.UserGroupService.GetUsername"/>
        /// </summary>
        public Beamable.Common.Promise<string> GetUsername(long gamerTag)
        {
            object raw_gamerTag = gamerTag;
            System.Collections.Generic.Dictionary<string, object> serializedFields = new System.Collections.Generic.Dictionary<string, object>();
            serializedFields.Add("gamerTag", raw_gamerTag);
            return this.Request<string>("UserGroupService", "GetUsername", serializedFields);
        }
    }
    
    internal sealed class MicroserviceParametersUserGroupServiceClient
    {
        
        [System.SerializableAttribute()]
        internal sealed class ParameterSystem_Int64 : MicroserviceClientDataWrapper<long>
        {
        }
        
        [System.SerializableAttribute()]
        internal sealed class ParameterSystem_String : MicroserviceClientDataWrapper<string>
        {
        }
    }
    
    [BeamContextSystemAttribute()]
    public static class ExtensionsForUserGroupServiceClient
    {
        
        [Beamable.Common.Dependencies.RegisterBeamableDependenciesAttribute()]
        public static void RegisterService(Beamable.Common.Dependencies.IDependencyBuilder builder)
        {
            builder.AddScoped<UserGroupServiceClient>();
        }
        
        public static UserGroupServiceClient UserGroupService(this Beamable.Server.MicroserviceClients clients)
        {
            return clients.GetClient<UserGroupServiceClient>();
        }
    }
}
