using System;
using System.Collections.Generic;
using System.Text;
using System.Threading.Tasks;
using Beamable;
using Beamable.Api.Autogenerated.Models;
using Beamable.Common.Models;
using Beamable.Server.Clients;
using TMPro;
using UnityEngine;
using UnityEngine.SceneManagement;
using Beamable.Serialization.SmallerJSON;

public class ChatRoom : MonoBehaviour
{
    private string _roomName;
    private BeamContext _beamContext;
    private BeamContext _beamContext01;
    
    private UserServiceClient _userService;
    private BackendServiceClient _backendService;
    private List<Message> _activeGroupChatMessages;

    private HashSet<string> _processedMessages;

    [SerializeField] 
    private TMP_Text roomNameText;
    [SerializeField]
    private TMP_Text chatLogText;
    [SerializeField]
    private TMP_InputField messageInput;

    private async void Start()
    {
        _processedMessages = new HashSet<string>();
        
        _beamContext = await BeamContext.Default.Instance;
        _beamContext01 = await BeamContext.ForPlayer("MyPlayer02").Instance;

        await _beamContext.Accounts.OnReady;
        await _beamContext01.Accounts.OnReady;
        
        _userService = new UserServiceClient();
        _backendService = new BackendServiceClient();

        _roomName = PlayerPrefs.GetString("SelectedRoomName", string.Empty);
        roomNameText.text = _roomName;

        await JoinRoom(_beamContext.PlayerId, _roomName);
        await JoinRoom(_beamContext01.PlayerId, _roomName);

        _beamContext.Api.NotificationService.Subscribe(_roomName, HandleNotification);
        
        LoadChatHistory();
        await SendGuestMessageAfterDelay(5f, "Hello from guest player!");
    }

    private async Task JoinRoom(long gamerTag, string roomName)
    {
        var response = await _backendService.JoinRoom(gamerTag, roomName);
        if (!response.data)
        {
            Debug.LogError($"Error joining room: {response.errorMessage}");
        }
    }

    private async void LoadChatHistory()
    {
        chatLogText.text = "";
        var response = await _backendService.GetRoomHistory(_roomName);
        if (!string.IsNullOrEmpty(response.errorMessage))
        {
            Debug.LogError($"Error loading chat history: {response.errorMessage}");
            return;
        }

        foreach (var message in response.data)
        {
            var username = await _userService.GetPlayerAvatarName(message.senderGamerTag);
            string roomMessage = $"{username.data}: {message.content}";
            chatLogText.text += $"{roomMessage}\n";
        }
    }

    public async void SendMessage()
    {
        if (!string.IsNullOrEmpty(messageInput.text))
        {
            var response = await _backendService.SendMessage(_beamContext.PlayerId, _roomName, messageInput.text);
            if (!response.data)
            {
                Debug.LogError($"Error sending message: {response.errorMessage}");
            }
            messageInput.text = "";
        }
    }

    private async Task SendGuestMessageAfterDelay(float delay, string message)
    {
        await Task.Delay(TimeSpan.FromSeconds(delay));
        
        var response = await _backendService.SendMessage(_beamContext01.PlayerId, _roomName, message);
        if (!string.IsNullOrEmpty(response.errorMessage))
        {
            Debug.LogError($"Error sending guest message: {response.errorMessage}");
        }
    }

    public async void ForgetRoom()
    {
        var response = await _backendService.LeaveRoom(_beamContext.PlayerId, _roomName);
        if (!response.data)
        {
            Debug.LogError($"Error leaving room: {response.errorMessage}");
        }
        else
        {
            SceneManager.LoadScene("ChatRooms");
        }
    }
    
    private async void HandleNotification(object payload)
    {
        Debug.Log($"Received payload: {payload}"); // Log the payload
        try
        {
            if (payload is ArrayDict arrayDict)
            {
                if (arrayDict.TryGetValue("stringValue", out var jsonString))
                {
                    var message = JsonUtility.FromJson<MessageData>(jsonString.ToString());
                    Debug.Log($"Message content: {message.senderGamerTag} {message.content}");
                    await UpdateChatLog(message);
                }
                else
                {
                    Debug.LogError("No 'stringValue' found in payload");
                }
            }
            else
            {
                Debug.LogError("Payload is not an ArrayDict");
            }
        }
        catch (Exception e)
        {
            Debug.LogError($"Error parsing payload: {e.Message}");
        }
    }

    private async Task UpdateChatLog(MessageData message)
    {
        var usernameResponse = await _userService.GetPlayerAvatarName(message.senderGamerTag);
        var roomMessage = $"{usernameResponse.data}: {message.content}";
        chatLogText.text += $"{roomMessage}\n";
    }
}
